# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMatrixCP <- function(x, y, hyperpars, elementMode) {
    .Call('_sparseGP_getMatrixCP', PACKAGE = 'sparseGP', x, y, hyperpars, elementMode)
}

deriveMatrixIndCP <- function(x, y, hyperpars, elementMode, dimIndex) {
    .Call('_sparseGP_deriveMatrixIndCP', PACKAGE = 'sparseGP', x, y, hyperpars, elementMode, dimIndex)
}

deriveMatrixHypCP <- function(x, y, hyperpars, selection, elementMode, singleDerive = FALSE) {
    .Call('_sparseGP_deriveMatrixHypCP', PACKAGE = 'sparseGP', x, y, hyperpars, selection, elementMode, singleDerive)
}

getMatrixSmap <- function(x, y, hyperpars, elementMode) {
    .Call('_sparseGP_getMatrixSmap', PACKAGE = 'sparseGP', x, y, hyperpars, elementMode)
}

getMatrix <- function(x, y, hyperpars, elementMode) {
    .Call('_sparseGP_getMatrix', PACKAGE = 'sparseGP', x, y, hyperpars, elementMode)
}

deriveMatrixInd <- function(x, y, hyperpars, elementMode, dimIndex) {
    .Call('_sparseGP_deriveMatrixInd', PACKAGE = 'sparseGP', x, y, hyperpars, elementMode, dimIndex)
}

deriveMatrixHyp <- function(x, y, hyperpars, selection, elementMode, singleDerive = FALSE) {
    .Call('_sparseGP_deriveMatrixHyp', PACKAGE = 'sparseGP', x, y, hyperpars, selection, elementMode, singleDerive)
}

fitSparseGPfD <- function(x, y, err, hyperpars) {
    .Call('_sparseGP_fitSparseGPfD', PACKAGE = 'sparseGP', x, y, err, hyperpars)
}

predictSparseGPfD <- function(model, px, reterr = TRUE) {
    .Call('_sparseGP_predictSparseGPfD', PACKAGE = 'sparseGP', model, px, reterr)
}

deriveSparseGPMarlikeIndfD <- function(model) {
    .Call('_sparseGP_deriveSparseGPMarlikeIndfD', PACKAGE = 'sparseGP', model)
}

deriveSparseGPMarlikeHypfD <- function(model, selection) {
    .Call('_sparseGP_deriveSparseGPMarlikeHypfD', PACKAGE = 'sparseGP', model, selection)
}

deriveSparseGPMarlikeDeltafD <- function(model, selection) {
    .Call('_sparseGP_deriveSparseGPMarlikeDeltafD', PACKAGE = 'sparseGP', model, selection)
}

deriveSparseGPMarlikeIndSelfD <- function(model, selection) {
    .Call('_sparseGP_deriveSparseGPMarlikeIndSelfD', PACKAGE = 'sparseGP', model, selection)
}

fitSparseGP <- function(x, y, err, hyperpars) {
    .Call('_sparseGP_fitSparseGP', PACKAGE = 'sparseGP', x, y, err, hyperpars)
}

predictSparseGP <- function(model, px, reterr = TRUE) {
    .Call('_sparseGP_predictSparseGP', PACKAGE = 'sparseGP', model, px, reterr)
}

getPostCovFromSparseGP <- function(px, py, model, elementMode, exact = FALSE) {
    .Call('_sparseGP_getPostCovFromSparseGP', PACKAGE = 'sparseGP', px, py, model, elementMode, exact)
}

preparePostSamplingFromSparseGP <- function(model, px, exact = FALSE) {
    .Call('_sparseGP_preparePostSamplingFromSparseGP', PACKAGE = 'sparseGP', model, px, exact)
}

getSamplesFromSparseGP <- function(sampleSpec, num, exact = FALSE) {
    .Call('_sparseGP_getSamplesFromSparseGP', PACKAGE = 'sparseGP', sampleSpec, num, exact)
}

deriveSparseGPMarlikeInd <- function(model) {
    .Call('_sparseGP_deriveSparseGPMarlikeInd', PACKAGE = 'sparseGP', model)
}

deriveSparseGPMarlikeHyp <- function(model, selection) {
    .Call('_sparseGP_deriveSparseGPMarlikeHyp', PACKAGE = 'sparseGP', model, selection)
}

deriveSparseGPMarlikeIndSel <- function(model, selection) {
    .Call('_sparseGP_deriveSparseGPMarlikeIndSel', PACKAGE = 'sparseGP', model, selection)
}

